export const INITIAL_COURSES = [
  {
    id: 1,
    title: 'Python Programming',
    instructor: 'John Smith',
    progress: 65,
    lessonsCount: 20,
    lessons: [
      { id: 101, title: 'Introduction to Python', isCompleted: true },
      { id: 102, title: 'Variables & Data Types', isCompleted: true },
      { id: 103, title: 'Control Flow & Conditionals', isCompleted: true },
      { id: 104, title: 'Loops & Iterations', isCompleted: true },
      { id: 105, title: 'Functions & Modules', isCompleted: true },
      { id: 106, title: 'Lists, Tuples & Dictionaries', isCompleted: true },
      { id: 107, title: 'Object-Oriented Programming (OOP)', isCompleted: true },
      { id: 108, title: 'Classes & Inheritance', isCompleted: true },
      { id: 109, title: 'Exception Handling', isCompleted: true },
      { id: 110, title: 'File I/O & Working with Data', isCompleted: true },
      { id: 111, title: 'Lambda Functions & List Comprehensions', isCompleted: true },
      { id: 112, title: 'Decorators & Generators', isCompleted: true },
      { id: 113, title: 'Virtual Environments & Pip', isCompleted: true },
      { id: 114, title: 'Standard Library Deep Dive', isCompleted: false },
      { id: 115, title: 'Working with JSON & APIs', isCompleted: false },
      { id: 116, title: 'Unit Testing with PyTest', isCompleted: false },
      { id: 117, title: 'Multithreading & AsyncIO', isCompleted: false },
      { id: 118, title: 'Web Scraping with BeautifulSoup', isCompleted: false },
      { id: 119, title: 'Database Integration (SQLite/SQLAlchemy)', isCompleted: false },
      { id: 120, title: 'Capstone Project: CLI Task Manager', isCompleted: false },
    ],
  },
  {
    id: 2,
    title: 'Generative AI',
    instructor: 'Sarah Williams',
    progress: 40,
    lessonsCount: 16,
    lessons: [
      { id: 201, title: 'Introduction to Large Language Models (LLMs)', isCompleted: true },
      { id: 202, title: 'Transformers Architecture & Attention Mechanisms', isCompleted: true },
      { id: 203, title: 'Prompt Engineering Fundamentals', isCompleted: true },
      { id: 204, title: 'Advanced Prompting Techniques (CoT, ReAct)', isCompleted: true },
      { id: 205, title: 'Embeddings & Vector Databases', isCompleted: true },
      { id: 206, title: 'Retrieval-Augmented Generation (RAG)', isCompleted: true },
      { id: 207, title: 'Fine-Tuning Strategies (LoRA, QLoRA)', isCompleted: false },
      { id: 208, title: 'AI Agents & Tool Calling', isCompleted: false },
      { id: 209, title: 'LangChain & LlamaIndex Frameworks', isCompleted: false },
      { id: 210, title: 'Diffusion Models & Image Generation', isCompleted: false },
      { id: 211, title: 'Multimodal AI Applications', isCompleted: false },
      { id: 212, title: 'Evaluation Metrics for Generative Models', isCompleted: false },
      { id: 213, title: 'Ethical AI, Safety & Guardrails', isCompleted: false },
      { id: 214, title: 'Deploying LLMs at Scale', isCompleted: false },
      { id: 215, title: 'Cost Optimization & Token Caching', isCompleted: false },
      { id: 216, title: 'Capstone Project: Autonomous Support Agent', isCompleted: false },
    ],
  },
  {
    id: 3,
    title: 'Full Stack Development',
    instructor: 'David Brown',
    progress: 25,
    lessonsCount: 28,
    lessons: [
      { id: 301, title: 'HTML5 Semantic Structure & Modern CSS', isCompleted: true },
      { id: 302, title: 'Modern JavaScript (ES6+) Core Concepts', isCompleted: true },
      { id: 303, title: 'Async JavaScript: Promises & Async/Await', isCompleted: true },
      { id: 304, title: 'React Fundamentals: Components & JSX', isCompleted: true },
      { id: 305, title: 'React State, Props & Lifecycle Hooks', isCompleted: true },
      { id: 306, title: 'Custom Hooks & State Management (Redux)', isCompleted: true },
      { id: 307, title: 'React Navigation & Routing', isCompleted: true },
      { id: 308, title: 'Styling with TailwindCSS & StyleSheet', isCompleted: false },
      { id: 309, title: 'Node.js Runtime & NPM Ecosystem', isCompleted: false },
      { id: 310, title: 'Building REST APIs with Express.js', isCompleted: false },
      { id: 311, title: 'Authentication with JWT & OAuth 2.0', isCompleted: false },
      { id: 312, title: 'PostgreSQL Relational Database & SQL', isCompleted: false },
      { id: 313, title: 'MongoDB Document Database & Mongoose', isCompleted: false },
      { id: 314, title: 'Database Indexing & Query Optimization', isCompleted: false },
      { id: 315, title: 'GraphQL Schema & Resolvers', isCompleted: false },
      { id: 316, title: 'Real-time Communication with WebSockets', isCompleted: false },
      { id: 317, title: 'API Security: CORS, Rate Limiting, Sanitization', isCompleted: false },
      { id: 318, title: 'Unit & Integration Testing with Jest', isCompleted: false },
      { id: 319, title: 'End-to-End Testing with Cypress', isCompleted: false },
      { id: 320, title: 'Docker Containers & Docker Compose', isCompleted: false },
      { id: 321, title: 'CI/CD Pipelines with GitHub Actions', isCompleted: false },
      { id: 322, title: 'Cloud Hosting & Serverless Functions', isCompleted: false },
      { id: 323, title: 'Redis Caching & Session Management', isCompleted: false },
      { id: 324, title: 'Web Vitals & Frontend Performance', isCompleted: false },
      { id: 325, title: 'Microservices Architecture Basics', isCompleted: false },
      { id: 326, title: 'Monitoring, Logging & Error Tracking', isCompleted: false },
      { id: 327, title: 'Production Deployment & Domain Setup', isCompleted: false },
      { id: 328, title: 'Capstone Project: Full Stack SaaS Platform', isCompleted: false },
    ],
  },
];

export default INITIAL_COURSES;
